#!/usr/bin/env python3
"""check_generated.py — prove the generated files still match their generators.

    python3 tools/check_generated.py        (CI runs this on every push)

Three files in this repo are output, not source: plan/CALENDAR.md, logs/PROGRESS.md and
logs/progress.json. Every document says so. Nothing enforced it, which meant a hand-edit
to the calendar would survive until the next `make calendar` silently reverted it — and
in the meantime the schedule you were reading would not be the schedule the tools knew
about.

This regenerates each one and compares. The only thing ignored is the "generated on"
date line in the progress report, which changes every day by design.

If this fails, you edited a generated file. Run `make calendar` and `make progress`, and
make the change in tools/schedule.py or in the source documents instead.
"""
import importlib.util
import io
import json
import os
import re
import sys
from contextlib import redirect_stdout

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DATE_LINE = re.compile(r"^Generated by `make progress` on \d{4}-\d{2}-\d{2}\.", re.M)


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def diff(label, want, have, hint):
    if want == have:
        return None
    w, h = want.splitlines(), have.splitlines()
    for i, (a, b) in enumerate(zip(w, h), 1):
        if a != b:
            return (f"{label}: differs from its generator at line {i}\n"
                    f"    on disk:    {b[:96]}\n"
                    f"    generated:  {a[:96]}\n"
                    f"  {hint}")
    return (f"{label}: differs from its generator in length "
            f"({len(h)} lines on disk, {len(w)} generated)\n  {hint}")


def main():
    problems = []

    sched = load("_schedule", os.path.join(ROOT, "tools", "schedule.py"))
    cal = os.path.join(ROOT, "plan", "CALENDAR.md")
    # The committed calendar carries relative day labels: logs/.start_date is
    # gitignored, so stamping it with real dates is a local choice, not a repo fact.
    want = sched.render(None) + "\n"
    have = open(cal).read() if os.path.exists(cal) else ""
    p = diff("plan/CALENDAR.md", want, have, "Fix: make calendar")
    if p:
        problems.append(p)

    prog = load("_progress", os.path.join(ROOT, "tools", "progress.py"))
    results = prog.score()
    md = os.path.join(ROOT, "logs", "PROGRESS.md")
    want = DATE_LINE.sub("", prog.render_md(results) + "\n")
    have = DATE_LINE.sub("", open(md).read() if os.path.exists(md) else "")
    p = diff("logs/PROGRESS.md", want, have, "Fix: make progress")
    if p:
        problems.append(p)

    js = os.path.join(ROOT, "logs", "progress.json")
    if os.path.exists(js):
        try:
            on_disk = json.load(open(js))
        except ValueError:
            problems.append("logs/progress.json: not valid JSON\n  Fix: make progress")
            on_disk = None
        if on_disk is not None:
            if on_disk.get("capabilities") != list(results.values()):
                problems.append("logs/progress.json: does not match `make progress` "
                                "output\n  Fix: make progress")
    else:
        problems.append("logs/progress.json: missing\n  Fix: make progress")

    if problems:
        for p in problems:
            print(p, file=sys.stderr)
        print(f"\n{len(problems)} generated file(s) out of date. These files are output, "
              f"not source — edit the generator, not the file.", file=sys.stderr)
        return 1
    print("generated files match their generators")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
